apiVersion: v1
kind: Service
metadata:
 name: hostname-svc-nlb
  ### 네트워크 로드 밸런서
 annotations:
   service.beta.kuberneties.io/aws-load-balancer-type: "nlb"
spec:
 ports:
  - name: web-port
    port: 80
    targetPort: 80
 selector:
  app: webserver
 type: LoadBalancer
